<?php

return [
    [
        'group_label' => 'الرئيسية',
        'items' => [
            [
                'label' => 'البوابة',
                'route' => 'viewer-new.hub',
                'active_key' => 'hub',
                'group_label' => 'الرئيسية',
                'icon_key' => 'home',
                'icon_svg' => 'M12 3l8 7h-2v9h-4v-6H10v6H6v-9H4l8-7z',
                'route_is' => ['viewer-new.hub'],
            ],
        ],
    ],
    [
        'group_label' => 'التقارير',
        'items' => [
            [
                'label' => 'التقارير',
                'route' => 'viewer-new.reports',
                'active_key' => 'reports',
                'group_label' => 'التقارير',
                'icon_key' => 'reports',
                'icon_svg' => 'M5 4h14v2H5V4zm0 5h14v2H5V9zm0 5h9v2H5v-2zm11 0h3v6h-3v-6z',
                'route_is' => ['viewer-new.reports'],
                'route_is_group' => ['viewer-new.reports.*'],
            ],
            [
                'label' => 'تقرير العقارات',
                'route' => 'viewer-new.reports.properties',
                'active_key' => 'reports.properties',
                'group_label' => 'التقارير',
                'icon_key' => 'report-properties',
                'icon_svg' => 'M4 20h16v-9l-8-7-8 7v9zm3-2v-5h3v5H7zm7 0v-7h3v7h-3z',
                'route_is' => ['viewer-new.reports.properties'],
            ],
            [
                'label' => 'تقرير المالك',
                'route' => 'viewer-new.reports.owners',
                'active_key' => 'reports.owners',
                'group_label' => 'التقارير',
                'icon_key' => 'report-owners',
                'icon_svg' => 'M12 12a4 4 0 100-8 4 4 0 000 8zm-7 8a7 7 0 0114 0H5z',
                'route_is' => ['viewer-new.reports.owners'],
            ],
            [
                'label' => 'تقرير الإشارات',
                'route' => 'viewer-new.reports.signals',
                'active_key' => 'reports.signals',
                'group_label' => 'التقارير',
                'icon_key' => 'report-signals',
                'icon_svg' => 'M4 19h16l-8-14-8 14zm8-3a1 1 0 110-2 1 1 0 010 2zm-1-4V9h2v3h-2z',
                'route_is' => ['viewer-new.reports.signals'],
            ],
            [
                'label' => 'تقرير الملحقات',
                'route' => 'viewer-new.reports.attachments',
                'active_key' => 'reports.attachments',
                'group_label' => 'التقارير',
                'icon_key' => 'report-attachments',
                'icon_svg' => 'M8 7a4 4 0 118 0v8a5 5 0 11-10 0V8h2v7a3 3 0 106 0V7a2 2 0 10-4 0v8h-2V7z',
                'route_is' => ['viewer-new.reports.attachments'],
            ],
        ],
    ],
    [
        'group_label' => 'الإحصاءات',
        'items' => [
            [
                'label' => 'الإحصاءات',
                'route' => 'viewer-new.statistics',
                'active_key' => 'statistics',
                'group_label' => 'الإحصاءات',
                'icon_key' => 'statistics',
                'icon_svg' => 'M5 18h3V9H5v9zm5 0h3V4h-3v14zm5 0h3v-6h-3v6z',
                'route_is' => ['viewer-new.statistics'],
                'route_is_group' => ['viewer-new.statistics.*'],
            ],
            [
                'label' => 'عامة',
                'route' => 'viewer-new.statistics.general',
                'active_key' => 'statistics.general',
                'group_label' => 'الإحصاءات',
                'icon_key' => 'statistics-general',
                'icon_svg' => 'M4 5h16v2H4V5zm0 6h10v2H4v-2zm0 6h16v2H4v-2z',
                'route_is' => ['viewer-new.statistics.general'],
            ],
            [
                'label' => 'مالية',
                'route' => 'viewer-new.statistics.financial',
                'active_key' => 'statistics.financial',
                'group_label' => 'الإحصاءات',
                'icon_key' => 'statistics-financial',
                'icon_svg' => 'M3 17l5-6 4 3 5-7 4 5-1.6 1.2-2.5-3.1-4.7 6.6-4.1-3-3.3 4z',
                'route_is' => ['viewer-new.statistics.financial'],
            ],
            [
                'label' => 'إدارية',
                'route' => 'viewer-new.statistics.administrative',
                'active_key' => 'statistics.administrative',
                'group_label' => 'الإحصاءات',
                'icon_key' => 'statistics-administrative',
                'icon_svg' => 'M4 6h16v12H4V6zm2 2v8h12V8H6zm2 2h8v2H8v-2z',
                'route_is' => ['viewer-new.statistics.administrative'],
            ],
            [
                'label' => 'سجل / مولد الإحصاءات',
                'route' => 'viewer-new.statistics.generator',
                'active_key' => 'statistics.generator',
                'group_label' => 'الإحصاءات',
                'icon_key' => 'statistics-generator',
                'icon_svg' => 'M6 4h9l5 5v11H6V4zm8 1.5V10h4.5L14 5.5zM8 14h8v2H8v-2z',
                'route_is' => ['viewer-new.statistics.generator'],
            ],
        ],
    ],
];
